from enum import StrEnum


class FaultType(StrEnum):
    BATTERY_DEGRADATION = 'BATTERY_DEGRADATION'
    LOW_BATTERY = 'LOW_BATTERY'
    SOLAR_PANEL_FAILURE = 'SOLAR_PANEL_FAILURE'
    HIGH_TEMPERATURE = 'HIGH_TEMPERATURE'
    ANTENNA_FAILURE = 'ANTENNA_FAILURE'
    GPS_FAILURE = 'GPS_FAILURE'
    STAR_TRACKER_FAILURE = 'STAR_TRACKER_FAILURE'
    REACTION_WHEEL_FAILURE = 'REACTION_WHEEL_FAILURE'
    MEMORY_ERROR = 'MEMORY_ERROR'
    CPU_OVERLOAD = 'CPU_OVERLOAD'
    THRUSTER_FAILURE = 'THRUSTER_FAILURE'


class FaultSeverity(StrEnum):
    INFO = 'INFO'
    WARNING = 'WARNING'
    CRITICAL = 'CRITICAL'
